"use client";

import { FormEvent, useState } from "react";
import { Leaf, LoaderCircle, Plus, Snowflake, X } from "lucide-react";
import { useHomecare } from "@/components/providers";

function Dialog({ open, title, eyebrow, onClose, children }: { open: boolean; title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/60 backdrop-blur-sm sm:items-center sm:p-6" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="w-full rounded-t-[28px] border border-white/10 bg-[#0d1b13] p-5 sm:max-w-lg sm:rounded-[28px] sm:p-6" role="dialog" aria-modal="true"><div className="flex items-start justify-between"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-2 text-2xl font-bold text-white">{title}</h2></div><button className="icon-button" onClick={onClose} aria-label={`Close ${title}`}><X className="size-5" /></button></div>{children}</section></div>;
}

export function AddPlantDialog() {
  const { data, addPlant } = useHomecare();
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { await addPlant({ name: String(form.get("name")), species: String(form.get("species") || "House plant"), roomId: String(form.get("roomId")), waterEveryDays: Number(form.get("waterEveryDays")), trimEveryDays: Number(form.get("trimEveryDays")) }); setOpen(false); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add plant."); } finally { setLoading(false); } };
  return <><button className="secondary-button" onClick={() => setOpen(true)}><Plus className="size-4" /> Add plant</button><Dialog open={open} title="Add a plant" eyebrow="New living thing" onClose={() => setOpen(false)}><form className="mt-6 space-y-4" onSubmit={submit}><label className="block"><span className="field-label">Plant name</span><input name="name" className="field-input mt-2" required maxLength={80} placeholder="e.g. Monstera" /></label><label className="block"><span className="field-label">Species</span><input name="species" className="field-input mt-2" maxLength={100} placeholder="Optional" /></label><label className="block"><span className="field-label">Room</span><select name="roomId" className="field-input mt-2" required>{data.rooms.map((room) => <option value={room.id} key={room.id}>{room.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label><span className="field-label">Water every</span><select name="waterEveryDays" className="field-input mt-2" defaultValue="7"><option value="3">3 days</option><option value="7">7 days</option><option value="10">10 days</option><option value="14">14 days</option><option value="21">21 days</option></select></label><label><span className="field-label">Trim every</span><select name="trimEveryDays" className="field-input mt-2" defaultValue="60"><option value="30">30 days</option><option value="45">45 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label></div>{error && <p className="text-sm text-rose-300" role="alert">{error}</p>}<button className="primary-button w-full" disabled={loading}>{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Leaf className="size-4" />}Save plant</button></form></Dialog></>;
}

export function AddACDialog() {
  const { data, addAC } = useHomecare();
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { await addAC({ name: String(form.get("name")), roomId: String(form.get("roomId")), maintenanceEveryMonths: Number(form.get("months")) }); setOpen(false); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add AC."); } finally { setLoading(false); } };
  return <><button className="secondary-button" onClick={() => setOpen(true)}><Plus className="size-4" /> Add AC</button><Dialog open={open} title="Add an AC" eyebrow="New unit" onClose={() => setOpen(false)}><form className="mt-6 space-y-4" onSubmit={submit}><label className="block"><span className="field-label">Unit name</span><input name="name" className="field-input mt-2" required maxLength={80} placeholder="e.g. Living room AC" /></label><label className="block"><span className="field-label">Room</span><select name="roomId" className="field-input mt-2" required>{data.rooms.map((room) => <option value={room.id} key={room.id}>{room.name}</option>)}</select></label><label className="block"><span className="field-label">Maintenance interval</span><select name="months" className="field-input mt-2" defaultValue="3"><option value="1">Every month</option><option value="2">Every 2 months</option><option value="3">Every 3 months</option><option value="6">Every 6 months</option><option value="12">Every year</option></select></label>{error && <p className="text-sm text-rose-300" role="alert">{error}</p>}<button className="primary-button w-full" disabled={loading}>{loading ? <LoaderCircle className="size-4 animate-spin" /> : <Snowflake className="size-4" />}Save AC</button></form></Dialog></>;
}
