"use client";

import { FormEvent, useMemo, useState } from "react";
import { BarChart3, CalendarDays, Check, CircleDollarSign, HandCoins, Pencil, TrendingDown, TrendingUp } from "lucide-react";
import { AppDialog } from "@/components/app-dialog";
import { useHomecare } from "@/components/providers";
import { qatarDate, qatarDateWithCurrentTime, formatQar } from "@/lib/homecare";
import type { CollectionOccurrence, CollectionTemplate, Profile } from "@/types/homecare";

function ContributionSettings({ profile, template }: { profile: Profile; template?: CollectionTemplate }) {
  const { saveCollectionTemplate } = useHomecare();
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setError(""); try { await saveCollectionTemplate({ profileId: profile.id, amount: Number(form.get("amount")), dueDay: Number(form.get("dueDay")), startMonth: `${String(form.get("startMonth"))}-01`, isActive: form.get("isActive") === "on" }); setOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save contribution."); } finally { setLoading(false); } };
  return <><button type="button" className="icon-button" onClick={() => setOpen(true)} aria-label={`Edit ${profile.name}'s contribution`}><Pencil className="size-4" /></button><AppDialog open={open} title={`${profile.name}'s contribution`} eyebrow="Monthly collection" onClose={() => !loading && setOpen(false)} className="sm:max-w-md"><form className="mt-5 space-y-4" onSubmit={submit}><label className="block"><span className="field-label">Fixed monthly amount (QAR)</span><input className="field-input mt-2" name="amount" type="number" min="0" step="0.01" defaultValue={template?.amount || 0} required /></label><div className="grid grid-cols-2 gap-3"><label><span className="field-label">Due day</span><input className="field-input mt-2" name="dueDay" type="number" min="1" max="31" defaultValue={template?.dueDay || 1} required /></label><label><span className="field-label">Start month</span><input className="field-input mt-2" name="startMonth" type="month" defaultValue={(template?.startMonth || `${qatarDate().slice(0, 7)}-01`).slice(0, 7)} required /></label></div><label className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 bg-white/[0.03] px-3"><input name="isActive" type="checkbox" defaultChecked={template?.isActive || false} className="size-4 accent-emerald-300" /><span className="text-sm font-semibold text-white">Collect every month</span></label><p className="text-xs leading-5 text-slate-400">Set QAR 0 or turn this off for the owner. Twelve months are generated automatically.</p>{error && <p className="text-sm text-rose-300">{error}</p>}<button className="primary-button w-full" disabled={loading}><Check className="size-4" />{loading ? "Saving…" : "Save contribution"}</button></form></AppDialog></>;
}

export function CollectionPaymentDialog({ item, compact = false }: { item: CollectionOccurrence; compact?: boolean }) {
  const { data, recordAction } = useHomecare();
  const person = data.profiles.find((profile) => profile.id === item.profileId);
  const [open, setOpen] = useState(false); const [amount, setAmount] = useState(String(item.remainingAmount)); const [mode, setMode] = useState<"today" | "pick">("today"); const [date, setDate] = useState(qatarDate()); const [error, setError] = useState("");
  const submit = () => { const value = Number(amount); if (!value || value <= 0 || value > item.remainingAmount) { setError(`Enter an amount up to ${formatQar(item.remainingAmount)}.`); return; } recordAction({ type: "collection", entityId: item.id, amount: value, occurredAt: mode === "today" ? new Date().toISOString() : qatarDateWithCurrentTime(date) }); setOpen(false); };
  return <><button type="button" className={compact ? "min-h-9 rounded-lg bg-emerald-300 px-2.5 text-[10px] font-black text-[#07110c]" : "primary-button px-4"} onClick={() => { setAmount(String(item.remainingAmount)); setError(""); setOpen(true); }}><HandCoins className={compact ? "size-3.5" : "size-4"} />Payment received</button><AppDialog open={open} title="Payment received" eyebrow={person?.name || "Housemate"} onClose={() => setOpen(false)} className="sm:max-w-md"><label className="mt-5 block"><span className="field-label">Amount received (QAR)</span><input className="field-input mt-2" type="number" min="0.01" max={item.remainingAmount} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><fieldset className="mt-4"><legend className="field-label">When?</legend><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" className={`chip min-h-11 justify-center ${mode === "today" ? "border-emerald-300/30 text-emerald-200" : ""}`} onClick={() => setMode("today")}>Today</button><button type="button" className={`chip min-h-11 justify-center ${mode === "pick" ? "border-emerald-300/30 text-emerald-200" : ""}`} onClick={() => setMode("pick")}>Pick a date</button></div></fieldset>{mode === "pick" && <input className="field-input mt-3" type="date" max={qatarDate()} value={date} onChange={(event) => setDate(event.target.value)} />}{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}<button type="button" className="primary-button mt-5 w-full" onClick={submit}><Check className="size-4" />Confirm receipt</button></AppDialog></>;
}

export function ProfitLossPage() {
  const { data } = useHomecare();
  const currentMonth = qatarDate().slice(0, 7);
  const allMonths = useMemo(() => Array.from(new Set([...data.financeSummaries.map((item) => item.month.slice(0, 7)), ...data.bills.map((item) => item.dueAt.slice(0, 7)), ...data.collections.map((item) => item.billingMonth.slice(0, 7))])).sort(), [data]);
  const [month, setMonth] = useState(allMonths.includes(currentMonth) ? currentMonth : allMonths.at(-1) || currentMonth);
  const collections = data.collections.filter((item) => item.billingMonth.startsWith(month));
  const expenses = data.bills.filter((item) => item.dueAt.startsWith(month));
  const summary = data.financeSummaries.find((item) => item.month.startsWith(month)) || { expectedCollections: collections.reduce((sum, item) => sum + item.expectedAmount, 0), actualCollections: collections.reduce((sum, item) => sum + item.receivedAmount, 0), expectedExpenses: expenses.reduce((sum, item) => sum + item.amount, 0), actualExpenses: expenses.filter((item) => item.paidAt).reduce((sum, item) => sum + item.amount, 0) };
  const expectedProfit = summary.expectedCollections - summary.expectedExpenses; const cashProfit = summary.actualCollections - summary.actualExpenses;
  const chart = allMonths.slice(-12).map((key) => { const row = data.financeSummaries.find((item) => item.month.startsWith(key)); return { key, collections: row?.actualCollections || 0, expenses: row?.actualExpenses || 0 }; }); const maxChart = Math.max(1, ...chart.flatMap((item) => [item.collections, item.expenses]));
  const monthLabel = new Intl.DateTimeFormat("en-QA", { month: "long", year: "numeric", timeZone: "Asia/Qatar" }).format(new Date(`${month}-01T12:00:00+03:00`));
  return <div><header className="page-header"><div><p className="eyebrow">Shared home finances</p><h1 className="page-title">Profit &amp; Loss</h1><p className="page-description">Collections minus rent, internet, water, and electricity.</p></div><label className="flex items-center gap-2"><CalendarDays className="size-4 text-emerald-300" /><span className="sr-only">Month</span><input className="field-input min-h-11 w-40" type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[["Expected collections",summary.expectedCollections,HandCoins,"text-violet-200"],["Collections received",summary.actualCollections,CircleDollarSign,"text-emerald-300"],["Expenses due",summary.expectedExpenses,BarChart3,"text-amber-200"],["Expenses paid",summary.actualExpenses,Check,"text-sky-200"],["Expected profit",expectedProfit,expectedProfit >= 0 ? TrendingUp : TrendingDown,expectedProfit >= 0 ? "text-emerald-300" : "text-rose-300"],["Cash profit",cashProfit,cashProfit >= 0 ? TrendingUp : TrendingDown,cashProfit >= 0 ? "text-emerald-300" : "text-rose-300"]].map(([label,value,Icon,color]) => { const CardIcon = Icon as typeof HandCoins; return <div className="summary-card" key={String(label)}><span className={`summary-icon bg-white/[0.04] ${color}`}><CardIcon className="size-5" /></span><div><p>{String(label)}</p><strong className={String(color)}>{formatQar(Number(value))}</strong></div></div>; })}</section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><section className="panel overflow-hidden"><div className="border-b border-white/[0.06] p-5"><h2 className="font-bold text-white">{monthLabel} collections</h2><p className="mt-1 text-xs text-slate-400">Partial receipts are supported.</p></div><div className="divide-y divide-white/[0.06]">{collections.length ? collections.map((item) => { const profile = data.profiles.find((person) => person.id === item.profileId); return <div key={item.id} className="flex flex-wrap items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-full text-xs font-black text-[#07110c]" style={{ backgroundColor: profile?.color }}>{profile?.initials}</span><div className="min-w-0 flex-1"><p className="font-bold text-white">{profile?.name}</p><p className="mt-1 text-xs text-slate-400">Received {formatQar(item.receivedAmount)} · Remaining {formatQar(item.remainingAmount)}</p></div><span className={`chip text-[10px] ${item.status === "paid" ? "text-emerald-200" : item.status === "partial" ? "text-amber-200" : "text-rose-200"}`}>{item.status}</span>{item.status !== "paid" && <CollectionPaymentDialog item={item} compact />}</div>; }) : <p className="p-6 text-sm text-slate-400">No contribution occurrences for this month.</p>}</div></section>
      <section className="panel overflow-hidden"><div className="border-b border-white/[0.06] p-5"><h2 className="font-bold text-white">Monthly contribution setup</h2><p className="mt-1 text-xs text-slate-400">The owner can stay inactive at QAR 0.</p></div><div className="divide-y divide-white/[0.06]">{data.profiles.map((profile) => { const template = data.collectionTemplates.find((item) => item.profileId === profile.id); return <div key={profile.id} className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-full text-xs font-black text-[#07110c]" style={{ backgroundColor: profile.color }}>{profile.initials}</span><div className="min-w-0 flex-1"><p className="font-bold text-white">{profile.name}</p><p className="mt-1 text-xs text-slate-400">{template?.isActive && template.amount > 0 ? `${formatQar(template.amount)} · due day ${template.dueDay}` : "Not collected"}</p></div><ContributionSettings profile={profile} template={template} /></div>; })}</div></section>
    </div>
    <section className="panel mt-6 p-5"><div className="flex items-center gap-3"><BarChart3 className="size-5 text-emerald-300" /><div><h2 className="font-bold text-white">12-month cash comparison</h2><p className="text-xs text-slate-400">Actual receipts versus expenses paid.</p></div></div><div className="mt-6 flex h-44 items-end gap-3 overflow-x-auto" aria-hidden="true">{chart.map((item) => <div key={item.key} className="flex min-w-12 flex-1 flex-col items-center gap-2"><div className="flex h-32 items-end gap-1"><span className="w-3 rounded-t bg-emerald-300" style={{ height: `${Math.max(3,(item.collections/maxChart)*100)}%` }} /><span className="w-3 rounded-t bg-amber-300" style={{ height: `${Math.max(3,(item.expenses/maxChart)*100)}%` }} /></div><span className="text-[10px] text-slate-400">{item.key.slice(5)}</span></div>)}</div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><caption className="sr-only">Monthly collections and expenses</caption><thead className="text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-3">Month</th><th>Collections</th><th>Expenses</th><th>Cash result</th></tr></thead><tbody className="divide-y divide-white/[0.06]">{chart.map((item) => <tr key={item.key}><td className="py-3 font-semibold text-white">{item.key}</td><td>{formatQar(item.collections)}</td><td>{formatQar(item.expenses)}</td><td className={item.collections-item.expenses >= 0 ? "text-emerald-300" : "text-rose-300"}>{item.collections-item.expenses >= 0 ? "▲" : "▼"} {formatQar(item.collections-item.expenses)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
